### ISSUE TITLE
Error  Lua 499 Error Lua 3489

### ISSUE THREAD

**Issue by Furyclover** [Sluimerstand/ProfessionShoppingList#103]
Currently using v10.1.5-006.zip

26x Usage: local schematic = C_TradeSkillUI.GetRecipeSchematic(recipeSpellID, isRecraft [, recipeLevel])
[string "=[C]"]: in function `GetRecipeSchematic'
[string "@ProfessionShoppingList/ProfessionShoppingList.lua"]:499: in function `pslTrackRecipe'
[string "@ProfessionShoppingList/ProfessionShoppingList.lua"]:3489: in function <...ns/ProfessionShoppingList/ProfessionShoppingList.lua:2420>

happened when logging in.
Locals:
(*temporary) = "Usage: local schematic = C_TradeSkillUI.GetRecipeSchematic(recipeSpellID, isRecraft [, recipeLevel])"

**Comment by Sluimerstand** [comment]
Hm, the only reason I can think of that PSL would try to track a recipe on log-in is if you were tracking a recipe through the native Blizzard tracking.
If you use `/psl clear` and relog, does the error still occur?

**Comment by Sluimerstand** [comment]
Closing this as there's been no response and I cannot reproduce the issue myself.
