### ISSUE TITLE
Add Renown KP quests

### ISSUE THREAD

**Issue by Sluimerstand** [Sluimerstand/ProfessionShoppingList#105]
![image](https://github.com/Sluimerstand/ProfessionShoppingList/assets/29845810/58a0c1af-50b8-44a5-9e74-2238c61aef28)

**Comment by chriser-** [comment]
| Skill         | Renown 1              | KP 1  | KP2   | Renown 2              | KP 1  | KP 2  | Item ID |
|--------       |--------               |-------|-------|--------               |-------|-------|--------|
| Alchemy       | Maruuk 14 & 24        | 72311 | 72314 | Valdrakken 14 & 24    | 70892 | 70889 | 201706 |
| Blacksmithing | Maruuk 14 & 24        | 72312 | 72315 | Valdrakken 14 & 24    | 72329 | 70909 | 201708 |
| Enchanting    | Dragonscale 14 & 23   | 72299 | 72304 | Iskaara 14 & 24       | 72318 | 72323 | 201709 |
| Engineering   | Dragonscale 14 & 23   | 72300 | 72305 | Valdrakken 14 & 24    | 72330 | 70902 | 201710 |
| Herbalism     | Maruuk 14 & 24        | 72313 | 72316 | Iskaara 14 & 24       | 72319 | 72324 | 201705 and 201717 |
| Inscription   | Dragonscale 14 & 23   | 72294 | 72295 | Valdrakken 14 & 24    | 72331 | 72334 | 201711 |
| Jewelcrafting | Dragonscale 14 & 23   | 72301 | 72306 | Iskaara 14 & 24       | 72320 | 72325 | 201712 |
| Leatherworking| Maruuk 14 & 24        | 72296 | 72297 | Iskaara 14 & 24       | 72321 | 72326 | 201713 |
| Mining        | Dragonscale 14 & 23   | 72302 | 72308 | Valdrakken 14 & 24    | 72332 | 72335 | 201700 and 201716 |
| Skinning      | Maruuk 14 & 24        | 72310 | 72317 | Iskaara 14 & 24       | 72322 | 72327 | 201714 and 201718 |
| Tailoring     | Dragonscale 14 & 23   | 72303 | 72309 | Valdrakken 14 & 24    | 72333 | 72336 | 201715 |

Dragonscale Quests are named `Expedition Crafting Knowledge` (yes only one name for both 14 & 23 Renown)
Maruuk Quests are named `A Gift of Knowledge` and `A Gift of Secrets`
Iskaara Quests are named `Iskaaran Crafter's Knowledge` and `Iskaaran Crafting Mastery`
Valdrakken Quests are named `Crafting Your Start` and `Crafting for Expertise`

**Comment by Sluimerstand** [comment]
This is (finally) added, with the next release. :)
