### ISSUE TITLE
Dragonflight - Hit track twice on a recipee and nothing went into the Reagents window

### ISSUE THREAD

**Issue by EyeSage** [Sluimerstand/ProfessionShoppingList#109]
![Screenshot 2023-09-09 114500](https://github.com/Sluimerstand/ProfessionShoppingList/assets/55958529/93fe5567-a37e-4458-8046-b9fb67ade5f3)

**Comment by EyeSage** [comment]
This worked for me yesterday for leatherworking when I used this addon for the first time.  I thought maybe the new version today caused it to fail, but I really don't know this well at all.

**Comment by EyeSage** [comment]
I did a reload and it worked so I have a work around.

**Comment by Sluimerstand** [comment]
Hi @EyeSage, is this on the 003 version? If so, this bug is likely resolved in the 004 version. I'd messed something up in that version that caused the list to bug out after using `/psl clear`.

Can you verify the bug is not present in the latest version? :)

**Comment by EyeSage** [comment]
Yes it works correctly now on version 4.   I got the error on version 3.
