### ISSUE TITLE
Add Darkmoon KP

### ISSUE THREAD

**Issue by chriser-** [Sluimerstand/ProfessionShoppingList#111]
All Darkmoon skill increase quests:
https://www.wowhead.com/quests/world-events/darkmoon-faire?filter=33:48;-2323:-2323;0:0
All that reward Mettle:
https://www.wowhead.com/quests/world-events/darkmoon-faire?filter=33:22;-2323:1;0:1
Table:
| Profession | Quest ID |
|--------|--------|
| Alchemy | 29506 | 
| Blacksmithing | 29508 | 
| Enchanting | 29510 | 
| Engineering | 29511 | 
| Herbalism | 29514 | 
| Inscription | 29515 | 
| Jewelcrafting | 29516 | 
| Leatherworking | 29517 |
| Mining | 29518 | 
| Skinning | 29519 | 
| Tailoring | 29520 | 

Some stuff inbetween is Cooking/Fishing/Archeology/Classic Skill, so no KP/Mettle.

**Comment by Sluimerstand** [comment]
I'll get to this soon, things have been a little hectic in my personal life lately. Thank you a lot for finding all the info I need to implement this!

**Comment by Sluimerstand** [comment]
This will be included in the next release, though it will only show up when the DMF is active.
