### ISSUE TITLE
Bug Error 11/14/23 

### ISSUE THREAD

**Issue by Furyclover** [Sluimerstand/ProfessionShoppingList#113]
4x ...eProfessionShoppingList/libs/lib-st/Core.lua:417: attempt to compare string with nil
[string "@ProfessionShoppingList/libs/lib-st/Core.lua"]:417: in function <...eProfessionShoppingList/libs/lib-st/Core.lua:356>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `sort'
[string "@ProfessionShoppingList/libs/lib-st/Core.lua"]:330: in function `SortData'
[string "@ProfessionShoppingList/libs/lib-st/Core.lua"]:613: in function `SetData'
[string "@ProfessionShoppingList/ProfessionShoppingList.lua"]:461: in function `UpdateRecipes'
[string "@ProfessionShoppingList/ProfessionShoppingList.lua"]:521: in function `Show'
[string "@ProfessionShoppingList/ProfessionShoppingList.lua"]:531: in function `Toggle'
[string "@ProfessionShoppingList/ProfessionShoppingList.lua"]:1466: in function `OnClick'
[string "@BigWigs/Libs/LibDBIcon-1.0-52/LibDBIcon-1.0.lua"]:170: in function <BigWigs/Libs/LibDBIcon-1.0/LibDBIcon-1.0.lua:168>

Locals:
self = <table> {
 sorttable = <table> {
 }
 filtered = <table> {
 }
 SetHeight = <function> defined @ProfessionShoppingList/libs/lib-st/Core.lua:38
 cols = <table> {
 }
 GetDefaultHighlightBlank = <function> defined @ProfessionShoppingList/libs/lib-st/Core.lua:450
 EnableSelection = <function> defined @ProfessionShoppingList/libs/lib-st/Core.lua:484
 scrollframe = ScrollTable2ScrollFrame {
 }
 Hide = <function> defined @ProfessionShoppingList/libs/lib-st/Core.lua:300
 offset = 0
 GetRow = <function> defined @ProfessionShoppingList/libs/lib-st/Core.lua:620
 showing = true
 Show = <function> defined @ProfessionShoppingList/libs/lib-st/Core.lua:290
 DefaultEvents = <table> {
 }
 SetWidth = <function> defined @ProfessionShoppingList/libs/lib-st/Core.lua:43
 Filter = <function> defined @ProfessionShoppingList/libs/lib-st/Core.lua:424
 SetFilter = <function> defined @ProfessionShoppingList/libs/lib-st/Core.lua:433
 GetSelection = <function> defined @ProfessionShoppingList/libs/lib-st/Core.lua:520
 SetSelection = <function> defined @ProfessionShoppingList/libs/lib-st/Core.lua:500
 DoFilter = <function> defined @ProfessionShoppingList/libs/lib-st/Core.lua:438
 isMinimalDataformat = true
 ClearSelection = <function> defined @ProfessionShoppingList/libs/lib-st/Core.lua:492
 data = <table> {
 }
 GetCell = <function> defined @ProfessionShoppingList/libs/lib-st/Core.lua:628
 rows = <table> {
 }
 multiselection = false
 SetData = <function> defined @ProfessionShoppingList/libs/lib-st/Core.lua:610
 SortData = <function> defined @ProfessionShoppingList/libs/lib-st/Core.lua:310
 FireUserEvent = <function> defined @ProfessionShoppingList/libs/lib-st/Core.lua:65
 GetDefaultHighlight = <function> defined @ProfessionShoppingList/libs/lib-st/Core.lua:465
 rowHeight = 15
 displayRows = 15
 defaulthighlightblank = <table> {
 }
 defaulthighlight = <table> {
 }
 RegisterEvents = <function> defined @ProfessionShoppingList/libs/lib-st/Core.lua:78
 head = ScrollTable2Head {
 }
 SetDefaultHighlightBlank = <function> defined @ProfessionShoppingList/libs/lib-st/Core.lua:454
 Refresh = <function> defined @ProfessionShoppingList/libs/lib-st/Core.lua:820
 SetDisplayCols = <function> defined @ProfessionShoppingList/libs/lib-st/Core.lua:203
 IsRowVisible = <function> defined @ProfessionShoppingList/libs/lib-st/Core.lua:645
 RowIsVisible = <function> defined @ProfessionShoppingList/libs/lib-st/Core.lua:645
 SetDefaultHighlight = <function> defined @ProfessionShoppingList/libs/lib-st/Core.lua:469
 events = <table> {
 }
 DoCellUpdate = <function> defined @ProfessionShoppingList/libs/lib-st/Core.lua:533
 SetHighLightColor = <function> defined @ProfessionShoppingList/libs/lib-st/Core.lua:57
 frame = ScrollTable2 {
 }
 SetDisplayRows = <function> defined @ProfessionShoppingList/libs/lib-st/Core.lua:122
 CompareSort = <function> defined @ProfessionShoppingList/libs/lib-st/Core.lua:356
}
rowa = 2
rowb = 1
sortbycol = 1
cella = "|cff0070dd|Hitem:194702::::::::70:256:::::::::|h[Draconic Treatise on Enchanting]|h|r"
cellb = nil
a1 = "|cff0070dd|Hitem:194702::::::::70:256:::::::::|h[Draconic Treatise on Enchanting]|h|r"
b1 = nil
column = <table> {
 bgcolor = <table> {
 }
 align = "LEFT"
 width = 150
 name = "Recipes"
 sort = 1
 color = <table> {
 }
 defaultsort = 1
}
direction = 1
(*temporary) = 1
(*temporary) = nil
(*temporary) = "nil"
(*temporary) = <table> {
 2 = 1
}
(*temporary) = nil
(*temporary) = "attempt to compare string with nil"
StringToNumber = <function> defined @ProfessionShoppingList/libs/lib-st/Core.lua:343
lib = <table> {
 CreateST = <function> define

**Comment by Sluimerstand** [comment]
Hi @Furyclover, I've been getting this myself as well but I've not been able to reproduce it reliably yet.
In the meantime you can use `/psl clear` to resolve the problem. Thank you for your report, I am looking into it!

**Comment by Sluimerstand** [comment]
... I figured it out. I'm a dumb-dumb. Hotfix version coming!
