### ISSUE TITLE
Renown KP quests incorrect Renown levels

### ISSUE THREAD

**Issue by Sluimerstand** [Sluimerstand/ProfessionShoppingList#120]
14 not 12
Dragonscale 23? Ugh

**Comment by Erenndriel** [comment]
I second this! Just came to Maruuks' at lvl 12 hoping to buy CK book and when I looked at the rewards panel, it says its a reward at lvl 14 instead.

![image](https://github.com/Sluimerstand/ProfessionShoppingList/assets/110241297/18a7c179-d0c1-4c32-9fea-03125f898076)

**Comment by Sluimerstand** [comment]
It's my bad! Someone provided all the info for me perfectly, but reading is hard apparently. :')
I'll have this fixed in the next release.

**Comment by albannurkollari** [comment]
> It's my bad! Someone provided all the info for me perfectly, but reading is hard apparently. :') I'll have this fixed in the next release.

I have a fix already! Creating a PR so pls test and approve if you will.

**Comment by albannurkollari** [comment]
Also, @Erenndriel is my alter GitHub acc! xD

**Comment by Sluimerstand** [comment]
I've solved it a little differently than your PR, with commit [af972e2](https://github.com/Sluimerstand/ProfessionShoppingList/commit/af972e202c3cd05f1a2376ebd912d6d001ae8340). This will be included in the next version release. :)
