### ISSUE TITLE
Add Option to change Quick Order Details+Mass Crafting Order Crafting (maybe, feels like a big ask)

### ISSUE THREAD

**Issue by Elandura** [Sluimerstand/ProfessionShoppingList#132]
Hello, I've recently started to discover your addon's features. My friends asked me to spam craft order to them and the option that addon has works great. But they want to be able to complete them in a more lax period of time. So, spamming quick orders only for 12 hours although it's good and preferable, they want me to do it on 24 to 48h and they tell me that they'll send me the postage value.
If this was just for my alts, base 12h option for the quick order would be great. Just something maybe you can add as a feature, thanks <3

**Comment by Elandura** [comment]
Also can you add mass order crafting option if you can ? So if we spam quick orders on an alt to a main, we can mass craft those orders then ?

**Comment by Sluimerstand** [comment]
I can look into adding a setting or slash command for the quick order duration, that should not be an issue. :)

Mass crafting work orders on the other hand is not really possible. You're only able to accept and work on one order at a time, and automating the several button presses needed to select, accept, craft, and complete a work order is very likely against Blizzard's terms of service, much in the same way automation on the Auction House is.

**Comment by Elandura** [comment]
Thanks for the quick response, though it's not as much complicated, accepting mail is kind of a similar process, and addons do mass mail accept functions. Maybe it wouldn't be as ToS-enemy, since doing the same thing on ah might affect the market, but mass accepting crafting orders like "obsidian seared alloy" etc might not be as bad, I don't know maybe my insomnia makes me miss things, or I'm being unintentionally obtuse because I want this so much, either way thank you my man. I like your work!

**Comment by Sluimerstand** [comment]
I completely understand your viewpoint, but Blizzard likely won't be as tolerable in that regard. It's not something I want to risk with this addon; I feel like if this wasn't disallowed or at the very least in grey area, another addon would exist with that particular functionality. :)

**Comment by Elandura** [comment]
For profession purposes, I've never seen any addon like yours, so I don't know about that. <3 I use your addon with enhanced crafting UI weakaura [](https://wago.io/6nUSNpGW8). Maybe you can add that weakaura's functionality to your addon and I delete that one as well. :)

Thanks for trying to show me the reasoning why it can't be though. I appreciate it. I hope you find a near-legit way to handle it. :)

**Comment by Sluimerstand** [comment]
I'll look into that WA, if I feel the changes are worth while and in line with what I see as the purpose of PSL I could definitely implement some of that. :D

**Comment by Sluimerstand** [comment]
I've added the option to set the quick order duration via a slash command: 42262f4
This will be included in the next release.

I'll take a look at that WeakAura some other time, I'll keep this issue open until then. :D

**Comment by Sluimerstand** [comment]
Alright, the WA is not really something that falls in line with PSL's functions, nor is it code I want to maintain. Closing this for now. The quick order duration will get a proper UI settings thing when I rework the settings page. :D
