### ISSUE TITLE
Lua errors after updateting to v10.2.7-001

### ISSUE THREAD

**Issue by Odysseas68** [Sluimerstand/ProfessionShoppingList#133]
After today update to v10.2.7-001 i have the following Lua error:

14x ...ofessionShoppingList/modules/ProfessionKnowledge.lua:576: attempt to index global 'knowledgePointTracker' (a nil value)
[string "@ProfessionShoppingList/modules/ProfessionKnowledge.lua"]:576: in function `KnowledgeTracker'
[string "@ProfessionShoppingList/modules/ProfessionKnowledge.lua"]:1085: in function `?'
[string "@ProfessionShoppingList/modules/ProfessionKnowledge.lua"]:17: in function <...ofessionShoppingList/modules/ProfessionKnowledge.lua:15>

Locals:
skillLineID = 0
professionID = nil
setKnowledgePointTracker = <function> defined @ProfessionShoppingList/modules/ProfessionKnowledge.lua:95
treatiseItem = nil
treatiseQuest = nil
orderQuest = nil
gatherQuests = nil
craftQuests = nil
drops = nil
hiddenMaster = nil
treasures = nil
books = nil
progress = true
kpTooltip = <function> defined @ProfessionShoppingList/modules/ProfessionKnowledge.lua:170
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'knowledgePointTracker' (a nil value)"
app = <table> {
 UpdateAssets = <function> defined @ProfessionShoppingList/Core.lua:2141
 QuickOrderAttempts = 0
 iconNotReady = "Interface\RaidFrame\ReadyCheck-NotReady"
 SelectedRecipeID = 0
 UpdateCooldowns = <function> defined @ProfessionShoppingList/Core.lua:580
 Settings = <function> defined @ProfessionShoppingList/Core.lua:2380
 NameLong = "|R|cffC69B6DProfession Shopping List|R"
 Clear = <function> defined @ProfessionShoppingList/Core.lua:2337
 OrderRecipeID = 0
 NameShort = "|R|cffC69B6DPSL|R"
 QuickOrderErrors = 0
 OpenSettings = <function> defined @ProfessionShoppingList/Core.lua:2356
 Show = <function> defined @ProfessionShoppingList/Core.lua:1657
 Dump = <function> defined @ProfessionShoppingList/Core.lua:35
 UpdateNumbers = <function> defined @ProfessionShoppingList/Core.lua:387
 CreateTradeskillAssets = <function> defined @ProfessionShoppingList/Core.lua:1904
 InitialiseCraftingOrders = <function> defined @ProfessionShoppingList/modules/CraftingOrders.lua:33
 MerchantFilter = <function> defined @ProfessionShoppingList/modules/Tweaks.lua:56
 Window = Frame {
 }
 iconReady = "Interface\RaidFrame\ReadyCheck-Ready"
 UpdatedReagentWidth = 0
 Flag = <table> {
 }
 CreateWindow = <function> defined @ProfessionShoppingList/Core.lua:239
 UpdateRecipes = <function> defined @ProfessionShoppingList/Core.lua:610
 UpdatedCooldownWidth = 0
 ReagentQuantities = <table> {
 }
 InitialiseCore = <function> defined @ProfessionShoppingList/Core.lua:116
 SaveWindow = <function> defined @ProfessionShoppingList/Core.lua:224
 slLegendaryRecipeIDs = <table> {
 }
 Toggle = <function> defined @ProfessionShoppingList/Core.lua:1676
 Legacy = <function> defined @ProfessionShoppingList/Core.lua:170
 iconProfession = <table> {
 }
 TooltipInfo = <function> defined @ProfessionShoppingList/Core.lua:2281
 QueueSound = <function> defined @ProfessionShoppingList/modules/Tweaks.lua:29
 KnowledgeTracker = <function> defined @ProfessionShoppingList/modules/ProfessionKnowledge.lua:89
 CreateProfessionKnowledgeAssets = <function> defined @ProfessionShoppingList/modules/ProfessionKnowledge.lua:41
 InitialiseProfessionKnowledge = <function> defined @ProfessionShoppingList/modules/ProfessionKnowledge.lua:29
 TrackRecipe = <function> defined @ProfessionShoppingList/Core.lua:1686
 nyiRecipes = <table> {
 }
 Hidden = Frame {
 }
 UntrackRecipe = <function> defined @ProfessionShoppingList/Core.lua:1769
 GetReagents = <function> defined @ProfessionShoppingList/Core.lua:312
 Popup = <function> defined @ProfessionShoppingList/Core.lua:57
 api = <table> {
 }
 Button = <function> defined @ProfessionShoppingList/Core.lua:95
 Print = <function> defined @ProfessionShoppingList/Core.lua:52
 iconWaiting = "Interface\RaidFrame\ReadyCheck-Waiting"
 CreateGeneralAssets = <function> defined @ProfessionShoppingList/Core.lua:1802
 CreateCraftingOrdersAssets = <function> defined @ProfessionShoppingList/mo

**Comment by Sluimerstand** [comment]
Fixed with b01d0d2.
