### ISSUE TITLE
Quick order for guild orders

### ISSUE THREAD

**Issue by B88000005** [Sluimerstand/ProfessionShoppingList#161]
The quick order feature is amazing.
That feature can only use for personal orders now. Could we add a feature for guild orders?
The reason is that we can't create cross-realm orders on personal order, but guild orders can do so.
Thanks a lot.

**Comment by Sluimerstand** [comment]
@B88000005 I'll include this in the next release. Use "GUILD" (all uppercase) as the recipient name, and it will create a Guild Order instead. :D
