### ISSUE TITLE
Having the crafting orders window and tradeskill window open, can result in wrong recipe tracked

### ISSUE THREAD

**Issue by Sluimerstand** [Sluimerstand/ProfessionShoppingList#184]
You know what to do

**Comment by cremor** [comment]
I also have this problem if only the crafting orders window is open.
But it never happens the first time. Only if I track multiple different recipes.

**Comment by Sluimerstand** [comment]
@cremor Is this for if you when you are tracking orders you can _place_, or when you are tracking orders you can _fulfill_?

**Comment by cremor** [comment]
Orders that I can place.

For one specific case I also noticed the following: After I searched for something in my own profession window, which I closed afterwards, the addon would only track the searched own recipe, even when I wanted to track crafting orders to place (from a profession I do not know myself). Only after I opened my profession window and cleared the search, then the tracking of crafting orders to place worked again.

**Comment by Sluimerstand** [comment]
Also add a warning for uncached recipes for tracking placing crafting orders.
