### ISSUE TITLE
Set Materials to BUY Even if they are Available

### ISSUE THREAD

**Issue by Mursanian** [Sluimerstand/ProfessionShoppingList#187]
Be able to toggle in the ProfessionShoppingList to still buy it even if having materials already, or able to craft them yourself.

**Comment by Sluimerstand** [comment]
Hi @Mursanian, what is the use case for this? Why would you/someone want to buy more materials than needed?

**Comment by Mursanian** [comment]
Use case would be to have it populate the auctionator shopping list, so one
sees the prizes for all tiers and can for example decide. Hey I can go for
t3 mats no issue.
Or maybe it counts your t3 mats but you actually don't wanna use those but
rather get t1 or t2. So it's in the list and you can easily grab other
tiers of the right amount. Saving your higher tiers, or getting higher
tiers cause they are cheap and save on potential concentration.

Sluimerstand ***@***.***> schrieb am Mi., 25. Sept. 2024,
08:45:

**Comment by Sluimerstand** [comment]
PSL actually accommodates that!
There is a setting: include higher quality in counts. There you can set if PSL should include tier 2/3 reagents, when counting tier 1 reagents. When you make a shopping list, PSL will respect that setting and show you how many more items you need for your preferences. When adding tier 1 reagents to the shopping list, Auctionator will also show tier 1+2+3 so you can see if any of them are cheaper. :)

**Comment by Mursanian** [comment]
Ahh alright. I guess that needs to be set before, tracking the recipe I
guess. I shall try once I get home from work. Thank you.

Sluimerstand ***@***.***> schrieb am Mi., 25. Sept. 2024,
14:50:
