### ISSUE TITLE
"tracking" from crafting order npc (placing a order) doesn't track the correct thing

### ISSUE THREAD

**Issue by chadmccune** [Sluimerstand/ProfessionShoppingList#193]
**AddOn version**
_For example v11.0.2-020

**Have you tried to /reload, used /psl clear if it is recipe-related, and checked the issue occurs with only PSL enabled?**
yes

**Describe the problem**
At the npc to place a crafting order, I'm wanting to "track" a recipe so i know what to buy at the AH to place the order.  In my case, i'm trying to track an inscription item on my alchemist/engineer.

**Comment by Sluimerstand** [comment]
Does the bug occur when you only have one of those two windows open at the same time?
Have you cached the profession yet for the recipe you're trying to track? (By opening Inscription on an alt, or via the Guild or other link.)

**Comment by chadmccune** [comment]
It appears to be related to having one of the items in my profession window
selected at some point....I didn't spend a lot of time trying to isolate
the flow that caused it, but a fresh reload with nothing else done doesn't
reproduce it, but then viewing something in my profession window or some
other action causes it.

**Comment by Sluimerstand** [comment]
Yeah, that's the same issue as #184 then. Closing this as a duplicate, but I am working on a fix for this. It just requires a pretty big internal rework and I need to make sure it's using the right recipe in the right place before I release that publicly. :)
