### ISSUE TITLE
Your addon is Preventing handynotes map icons from being created using hotkeys. 

### ISSUE THREAD

**Issue by Booggg** [Sluimerstand/ProfessionShoppingList#194]
**AddOn version**
latest

**Describe the problem**
With this addon enabled, my handynotes hotkey to create map icons doesnt not work and creates a tomtom coords pin instead.

**Comment by Sluimerstand** [comment]
Hi @Booggg, if you disable the setting for it and `/reload`, PSL won't do that anymore.
![image](https://github.com/user-attachments/assets/a088981c-de2e-4715-986e-3ac3d0351519)
