### ISSUE TITLE
Tooltip Errors with ElvUI

### ISSUE THREAD

**Issue by xdreaper15** [Sluimerstand/ProfessionShoppingList#208]
**AddOn version**
 v11.0.2-026

**Have you tried to /reload, used /psl clear if it is recipe-related, and checked the issue occurs with only PSL enabled?**
Yes, this continues to occur, even when the psl window isn't present

**Have you taken a look at the addon's settings yet, to see if it's a feature that can be adjusted or disabled?**
I would like to keep the tooltip information 😅

**Describe the problem**

Error #1:
`10792x ...aceProfessionShoppingList/modules/Tweaks.lua:138: attempt to call global 'OEMarketInfo' (a nil value)
[string "@ProfessionShoppingList/modules/Tweaks.lua"]:138: in function <...aceProfessionShoppingList/modules/Tweaks.lua:117>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:61: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:56>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:81: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:77>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:117: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:107>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:142: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:135>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:288: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:238>
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:235: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:234>
[string "=(tail call)"]: ?
...
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:422: in function `UIParentLoadAddOn'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:627: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:96: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:89: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:84: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:76: in function <...pansionLandingPage/Blizzard_WarWithinLandingPage.lua:72>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:48: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:82: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:37: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:35>

Locals:
tooltip = ElvUI_ScanTooltip {
 shadow = Frame {
 }
 BottomOverlay = Texture {
 }
 NineSlice = Frame {
 }
 textLeft1Font = "GameTooltipHeaderText"
 hasMoney = 1
 textRight2Font = "GameTooltipText"
 TopOverlay = Texture {
 }
 TextLeft1 = ElvUI_ScanTooltipTextLeft1 {
 }
 StatusBar = ElvUI_ScanTooltipStatusBar {
 }
 numMoneyFrames = 1
 supportsDataRefresh = true
 shownMoneyFrames = 1
 processingInfo = <table> {
 }
 infoList = <table> {
 }
 style = Frame {
 }
 textRight1Font = "GameTooltipHeaderText"
 updateTooltipTimer = 0.200000
 TextRight1 = ElvUI_ScanTooltipTextRight1 {
 }
 layoutType = "TooltipDefaultLayout"
 textLeft2Font = "GameTooltipText"
 TextRight2 = ElvUI_ScanTooltipTextRight2 {
 }
 TextLeft2 = ElvUI_ScanTooltipTextLeft2 {
 }
}
_ = "Gatecrasher's Horns"
unreliableItemLink = "|cffa335ee|Hitem:212047::::::::80:270::35:7:10371:10390:6652:10876:10262:1520:10255:1:28:2462:::::|h[Gatecrasher's Horns]|h|r"
itemID = 212047
_ = "Gatecrasher's Horns"
itemLink = "|cffa335ee|Hitem:212047::::::::80:270:::::::::|h[Gatecrasher's Horns]|h|r"
loaded = true
finished = true
marketPrice = 0
regionPrice = 0
oeData = <table> {
}
(*temporary) = nil
(*temporary) = "|cffa335ee|Hitem:212047::::::::80:270:::::::::|h[Gatecrasher's Horns]|h|r"
(*temporary) = <table> {
}
(*temporary) = "attempt to call global 'OEMarketInfo' (a nil value)"
L = <table> {
 BUTTON_TRACKNEW = "Track new mogs"
 SETTINGS_CATALYSTBUTTON_TITLE = "Show Catalyst Button"
 ERROR_WARBANK = "Error: Can't create a Quick Order with items in the Warbank."
 TRACK_NEW2 = "visible recipes for"
 MILLING_MOP = "Misty Pigment: 25%, 50% from Fool's Cap
Shadow Pigment: 100%"
 SETTINGS_REAGENTQUALITY_TITLE = "Minimum Reagent Quality"
 SETTINGS_TOOLTIP = "|TInterface\TutorialFrame\UI-Tutorial-Frame:12:12:0:0:512:512:10:65:228:283|t|cffFFFFFF: Toggle the window.
|TInterface\TutorialFrame\UI-Tutorial-Frame:12:12:0:0:512:512:10:65:330:385|t: Show the settings."
 SETTINGS_APPEARANCES_TITLE = "Appearances"
 FALSE = "false"
 MILLING_TBC = "Ebon Pigment: 25%
Nether Pigment: 100%"
 READY = "Ready"
 SETTINGS_CLOSEWHENDONE_TITLE = "Close Window When Done"
 REGION = "Region"
 SETTINGS_INCLUDE = "Include"
 SETTINGS_PERSONALRECIPES_TITLE = "Track Recipes per Character"
 MILLING_SL = "Tranquil Pigment: Nightshade
Luminous Pigment: Death Blossom, Rising Glory, Vigil's Torch
Umbral Pigment: Death's Blossom, Marrowroot, Widowbloom"
 SETTINGS_PERSONALWINDOWS_TITLE = "Window Position per Character"
 SETTINGS_CLEANBAG_TOOLTIP = "Let |cffC69B6DPSL|r enforce cleanup sorting direction.
- Default means |cffC69B6DPSL|r won't touch the game's default behavior.
- The other options let |cffC69B6DPSL|r enforce that particular setting."
 DEBUG_ENABLED = "Debug mode enabled."
 SETTINGS_PERSONALRECIPES_TOOLTIP = "Track recipes per character, instead of account wide."
 SETTINGS_ORIBOSEXCHANGEFIX_TOOLTIP = "Let |cffC69B6DPSL|r simplify and fix the tooltip provided by the Oribos Exchange AddOn:
- Round to the nearest gold.
- Fix recipe prices.
- Fix profession window prices.
- Show battle pet prices inside the existing tooltip."
 RECHARGED = "Fully recharged"
 SETTINGS_SLASH_TOGGLE = "Toggle the tracking window."
 ADDED_RECIPES1 = "Added"
 WINDOW_BUTTON_LOCK = "Lock the window."
 NOLASTORDER = "No last Quick Order found."
 WINDOW_HEADER_REAGENTS = "Reagents"
 MILLING_WOD = "Cerulean Pigment: 100%"
 MINUTES = "m"
 RECRAFT_TOOLTIP = "Select an item with a cached recipe to track it.
To cache a recipe, open the profession the recipe belongs to on any character
or view the item as a regular crafting order."
 SETTINGS_HEADER_TWEAKS = "Tweaks"
 SETTINGS_CRAFTTOOLTIP_TITLE = "Show Crafting Information"
 CATALYSTBUTTON_LABEL = "Instantly Catalyze"
 WINDOW_TOOLTIP_COOLDOWNS = "Shift |TInterface\TutorialFrame\UI-Tutorial-Frame:12:12:0:0:512:512:10:65:330:385|t|cffFFFFFF: Remove this specific cooldown reminder.
|rCtrl |TInterface\TutorialFrame\UI-Tutorial-Frame:12:12:0:0:512:512:10:65:228:283|t|cffFFFFFF: Open the recipe (if known).
|rAlt |TInterface\TutorialFrame\UI-Tutorial-Frame:12:12:0:0:512:512:10:65:228:283|t|cffFFFFFF: Attemp`

Error #2
`6x ...aceProfessionShoppingList/modules/Tweaks.lua:232: attempt to call global 'OETooltip' (a nil value)
[string "@ProfessionShoppingList/modules/Tweaks.lua"]:232: in function `HideOribos'
[string "@ProfessionShoppingList/modules/Tweaks.lua"]:18: in function `handler'
[string "@ProfessionShoppingList/Core.lua"]:34: in function <ProfessionShoppingList/Core.lua:31>

Locals:
loaded = true
finished = true
(*temporary) = nil
(*temporary) = false
(*temporary) = "attempt to call global 'OETooltip' (a nil value)"
`

**Comment by Sluimerstand** [comment]
Hm, something weird is happening with the data from the Oribos Exchange addon.

I have a setting in the Tweaks category to fix its pricing display (as the addon dev refuses to implement the fixes themselves), and the code that is giving errors here only runs if the setting is enabled and Oribos Exchange is loaded. But somehow it's not able to read the info from Oribos Exchange and that is causing the issue.

That should not be something that's unique to ElvUI, does the error not occur when it's disabled?
Does the error still occur when Oribos Exchange is disabled? Can you try re-installing Oribos Exchange to see if that resolves the issue?

**Comment by xdreaper15** [comment]
Ahh, tbh I was assuming ElvUI due to the 'tooltip = ElvUI_ScanTooltip {', but disabling oribosexchange seems to have solved the problem

**Comment by Sluimerstand** [comment]
You can also disable the "Fix Oribos Exchange tooltip" setting from PSL if you want to keep Oribos Exchange enabled, but I assume Oribos Exchange wasn't providing you with any tooltip information anyway?

**Comment by xdreaper15** [comment]
Yeah, i've committed the ultimate sin of not knowing why i have an addon installed (Oribos Exchange)

**Comment by Sluimerstand** [comment]
Hahaha, gotcha. 👍

I'll add in a little failsafe anyway, in case there are other people out there with an outdated version of Oribos Exchange.
I personally enjoy using it a lot for AH prices, since it updates like 4 times a week, so by updating my addons I can have accurate AH prices without having to scan the AH or relying on an application like TSM needs.
