### ISSUE TITLE
Tailoring / Auctionator

### ISSUE THREAD

**Issue by zalidthebur** [Sluimerstand/ProfessionShoppingList#215]
**AddOn version**
19.1.0

**Describe the problem**
Get this comstantly on first opening up my Tailoring window:
12x Auctionator/Source/API/Internal.lua:2: Contact the maintainer of CraftSim to resolve this problem. Details: Usage Auctionator.API.v1.GetVendorPriceByItemLink(string, string)
[string "=[C]"]: in function `error'
[string "@Auctionator/Source/API/Internal.lua"]:2: in function `ComposeError'
[string "@Auctionator/Source/API/v1/GetVendorPrice.lua"]:18: in function `GetVendorPriceByItemLink'
[string "@CraftSim/Pricing/PriceAPIs.lua"]:214: in function `GetMinBuyoutByItemLink'
[string "@CraftSim/Pricing/PriceSource.lua"]:103: in function `GetMinBuyoutByItemLink'
[string "@CraftSim/Classes/PriceData.lua"]:201: in function `Update'
[string "@CraftSim/Classes/RecipeData.lua"]:264: in function `new'
[string "@CraftSim/Libs/classic.lua"]:64: in function `RecipeData'
[string "@CraftSim/Init/Init.lua"]:593: in function `TriggerModulesByRecipeType'
[string "@CraftSim/Init/Init.lua"]:85: in function <CraftSim/Init/Init.lua:83>
[string "@CraftSim/Libs/GUTIL/GUTIL.lua"]:606: in function <CraftSim/Libs/GUTIL/GUTIL.lua:600>

Locals:
(*temporary) = "Contact the maintainer of CraftSim to resolve this problem. Details: Usage Auctionator.API.v1.GetVendorPriceByItemLink(string, string)"

**Comment by Sluimerstand** [comment]
The error is thrown by Auctionator. It mentions that the error is caused by CraftSim, and to contact its developer.

Nowhere does it mention Profession Shopping List. This issue is not related to my AddOn. I suggest doing what the error tells you, and to contact CraftSim's developer instead.

**Comment by zalidthebur** [comment]
Oops. Sorry about that. Brain fart. That'll teach me to check the link I am following ;-)
