### ISSUE TITLE
Add Tooltip Here (picture)

### ISSUE THREAD

**Issue by Machou** [Sluimerstand/ProfessionShoppingList#219]
Hi, there,

Sorry about the title, I didn't know how to say it :D

Here, in a few Profession, I have the 2 icons (see screenshot) and I'm not sure what they are for some.

Could you add an explanatory tooltip?

Regards

![WoWScrnShot_110224_162300](https://github.com/user-attachments/assets/0d222831-bb71-4cef-8f34-b70bac09ac3f)

**Comment by Sluimerstand** [comment]
Fixed with 8a3fa41. :)
