### ISSUE TITLE
There's a bug report - still works tho.

### ISSUE THREAD

**Issue by Starvoicereason** [Sluimerstand/ProfessionShoppingList#22]
This is what I'm getting. I tried deleting the lua as that had fixed my bagnon, but no joy. I haven't stress tested it, but they appeared blank until I clicked it. It still works as it did, for single items, in both mats and recipes windows. (Complete with only able to remove on a character WITH that Profession.) Didn't check nested. 

Side note, so far as I can tell, a lot of my addons were made with or reference Ace3 and that's borked rn. No idea if this is being affected.

Anyway, just thought I'd let you know! 

Message: ...e/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:417: attempt to compare string with nil
Time: Fri Oct 28 20:41:46 2022
Count: 11
Stack: ...e/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:417: attempt to compare string with nil
[string "@Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua"]:417: in function <...e/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:356>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `sort'
[string "@Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua"]:330: in function `SortData'
[string "@Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua"]:613: in function `SetData'
[string "@Interface/AddOns/ProfessionShoppingList/ProfessionShoppingList.lua"]:240: in function `pslReagents'
[string "@Interface/AddOns/ProfessionShoppingList/ProfessionShoppingList.lua"]:1316: in function <...ns/ProfessionShoppingList/ProfessionShoppingList.lua:352>

Locals: self = <table> {
 sorttable = <table> {
 }
 filtered = <table> {
 }
 SetHeight = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:38
 cols = <table> {
 }
 GetDefaultHighlightBlank = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:450
 EnableSelection = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:484
 scrollframe = ScrollTable1ScrollFrame {
 }
 Hide = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:300
 offset = 0
 GetRow = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:620
 showing = true
 Show = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:290
 DefaultEvents = <table> {
 }
 SetWidth = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:43
 Filter = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:424
 SetFilter = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:433
 GetSelection = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:520
 SetSelection = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:500
 DoFilter = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:438
 isMinimalDataformat = true
 ClearSelection = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:492
 data = <table> {
 }
 GetCell = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:628
 rows = <table> {
 }
 multiselection = false
 SetData = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:610
 SortData = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:310
 FireUserEvent = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:65
 GetDefaultHighlight = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:465
 rowHeight = 15
 displayRows = 15
 defaulthighlightblank = <table> {
 }
 defaulthighlight = <table> {
 }
 RegisterEvents = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:78
 head = ScrollTable1Head {
 }
 SetDefaultHighlightBlank = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:454
 Refresh = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:820
 SetDisplayCols = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:203
 IsRowVisible = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:645
 RowIsVisible = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:645
 SetDefaultHighlight = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:469
 events = <table> {
 }
 DoCellUpdate = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:533
 SetH

**Comment by Starvoicereason** [comment]
Just found another. Forgot to turn the page. Though this MIGHT have been generated when I clicked the blank windows (Which made them blink and then populate).

Message: ...e/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:417: attempt to compare nil with string
Time: Fri Oct 28 20:50:46 2022
Count: 1
Stack: ...e/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:417: attempt to compare nil with string
[string "@Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua"]:417: in function <...e/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:356>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `sort'
[string "@Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua"]:330: in function `SortData'
[string "@Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua"]:613: in function `SetData'
[string "@Interface/AddOns/ProfessionShoppingList/ProfessionShoppingList.lua"]:240: in function `pslReagents'
[string "@Interface/AddOns/ProfessionShoppingList/ProfessionShoppingList.lua"]:384: in function `OnClick'
[string "@Interface/AddOns/BigWigs/Libs/LibDBIcon-1.0/LibDBIcon-1.0.lua"]:144: in function <.../AddOns/BigWigs/Libs/LibDBIcon-1.0/LibDBIcon-1.0.lua:142>

Locals: self = <table> {
 sorttable = <table> {
 }
 filtered = <table> {
 }
 SetHeight = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:38
 cols = <table> {
 }
 GetDefaultHighlightBlank = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:450
 EnableSelection = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:484
 scrollframe = ScrollTable1ScrollFrame {
 }
 Hide = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:300
 offset = 0
 GetRow = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:620
 showing = true
 Show = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:290
 DefaultEvents = <table> {
 }
 SetWidth = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:43
 Filter = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:424
 SetFilter = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:433
 GetSelection = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:520
 SetSelection = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:500
 DoFilter = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:438
 isMinimalDataformat = true
 ClearSelection = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:492
 data = <table> {
 }
 GetCell = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:628
 rows = <table> {
 }
 multiselection = false
 SetData = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:610
 SortData = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:310
 FireUserEvent = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:65
 GetDefaultHighlight = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:465
 rowHeight = 15
 displayRows = 15
 defaulthighlightblank = <table> {
 }
 defaulthighlight = <table> {
 }
 RegisterEvents = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:78
 head = ScrollTable1Head {
 }
 SetDefaultHighlightBlank = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:454
 Refresh = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:820
 SetDisplayCols = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:203
 IsRowVisible = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:645
 RowIsVisible = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:645
 SetDefaultHighlight = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:469
 events = <table> {
 }
 DoCell

**Comment by Starvoicereason** [comment]
Just found another. Forgot to turn the page. Though this MIGHT have been generated when I clicked the blank windows (Which made them blink and then populate).

Message: ...e/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:417: attempt to compare nil with string
Time: Fri Oct 28 20:50:46 2022
Count: 1
Stack: ...e/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:417: attempt to compare nil with string
[string "@Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua"]:417: in function <...e/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:356>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `sort'
[string "@Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua"]:330: in function `SortData'
[string "@Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua"]:613: in function `SetData'
[string "@Interface/AddOns/ProfessionShoppingList/ProfessionShoppingList.lua"]:240: in function `pslReagents'
[string "@Interface/AddOns/ProfessionShoppingList/ProfessionShoppingList.lua"]:384: in function `OnClick'
[string "@Interface/AddOns/BigWigs/Libs/LibDBIcon-1.0/LibDBIcon-1.0.lua"]:144: in function <.../AddOns/BigWigs/Libs/LibDBIcon-1.0/LibDBIcon-1.0.lua:142>

Locals: self = <table> {
 sorttable = <table> {
 }
 filtered = <table> {
 }
 SetHeight = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:38
 cols = <table> {
 }
 GetDefaultHighlightBlank = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:450
 EnableSelection = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:484
 scrollframe = ScrollTable1ScrollFrame {
 }
 Hide = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:300
 offset = 0
 GetRow = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:620
 showing = true
 Show = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:290
 DefaultEvents = <table> {
 }
 SetWidth = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:43
 Filter = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:424
 SetFilter = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:433
 GetSelection = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:520
 SetSelection = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:500
 DoFilter = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:438
 isMinimalDataformat = true
 ClearSelection = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:492
 data = <table> {
 }
 GetCell = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:628
 rows = <table> {
 }
 multiselection = false
 SetData = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:610
 SortData = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:310
 FireUserEvent = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:65
 GetDefaultHighlight = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:465
 rowHeight = 15
 displayRows = 15
 defaulthighlightblank = <table> {
 }
 defaulthighlight = <table> {
 }
 RegisterEvents = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:78
 head = ScrollTable1Head {
 }
 SetDefaultHighlightBlank = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:454
 Refresh = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:820
 SetDisplayCols = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:203
 IsRowVisible = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:645
 RowIsVisible = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:645
 SetDefaultHighlight = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:469
 events = <table> {
 }
 DoCell





This popped up after hitting sort on the default bags. And on my bags with Bagnon on, so... sorting and counting? Dunno.


Message: ...e/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:417: attempt to compare nil with string
Time: Fri Oct 28 21:23:37 2022
Count: 76
Stack: ...e/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:417: attempt to compare nil with string
[string "@Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua"]:417: in function <...e/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:356>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `sort'
[string "@Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua"]:330: in function `SortData'
[string "@Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua"]:613: in function `SetData'
[string "@Interface/AddOns/ProfessionShoppingList/ProfessionShoppingList.lua"]:240: in function `pslReagents'
[string "@Interface/AddOns/ProfessionShoppingList/ProfessionShoppingList.lua"]:1316: in function <...ns/ProfessionShoppingList/ProfessionShoppingList.lua:352>

Locals: self = <table> {
 sorttable = <table> {
 }
 filtered = <table> {
 }
 SetHeight = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:38
 cols = <table> {
 }
 GetDefaultHighlightBlank = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:450
 EnableSelection = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:484
 scrollframe = ScrollTable1ScrollFrame {
 }
 Hide = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:300
 offset = 0
 GetRow = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:620
 showing = true
 Show = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:290
 DefaultEvents = <table> {
 }
 SetWidth = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:43
 Filter = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:424
 SetFilter = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:433
 GetSelection = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:520
 SetSelection = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:500
 DoFilter = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:438
 isMinimalDataformat = true
 ClearSelection = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:492
 data = <table> {
 }
 GetCell = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:628
 rows = <table> {
 }
 multiselection = false
 SetData = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:610
 SortData = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:310
 FireUserEvent = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:65
 GetDefaultHighlight = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:465
 rowHeight = 15
 displayRows = 15
 defaulthighlightblank = <table> {
 }
 defaulthighlight = <table> {
 }
 RegisterEvents = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:78
 head = ScrollTable1Head {
 }
 SetDefaultHighlightBlank = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:454
 Refresh = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:820
 SetDisplayCols = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:203
 IsRowVisible = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:645
 RowIsVisible = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:645
 SetDefaultHighlight = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:469
 events = <table> {
 }
 DoCellUpdate = <function> defined @Interface/AddOns/ProfessionShoppingList/libs/lib-st/Core.lua:533
 SetH

**Comment by Sluimerstand** [comment]
Hello!

Have you used /psl clear after installing the Dragonflight version? I forgot to mention that in the release notes, but because of some changes in the code that step is more or less necessary to prevent things from going entirely wonky.

**Comment by Starvoicereason** [comment]
I have not! Give me a second..... Yep, no more errors popping up! Thanks! Not that the errors were stopping me from using it, lol.
As always! Amazing work!

**Comment by Starvoicereason** [comment]
I have not! Give me a second..... Yep, no more errors popping up! Thanks! Not that the errors were stopping me from using it, lol.
As always! Amazing work!
