### ISSUE TITLE
Option to close psl windows when crafting done

### ISSUE THREAD

**Issue by Sluimerstand** [Sluimerstand/ProfessionShoppingList#37]

**Comment by Sluimerstand** [comment]
Done.

**Comment by ergh99** [comment]
This isn't working for me.  The sub option check box remains checked and `/psl clear` had no effect

**Comment by Sluimerstand** [comment]
Hi @ergh99,
I see now why it wasn't working for crafting orders specifically. I'll get this fixed in the next release. :)
