### ISSUE TITLE
Spinoff knowledge tracking bar into a separate addon

### ISSUE THREAD

**Issue by chilblane** [Sluimerstand/ProfessionShoppingList#50]
I really like the knowledge tracking bar as a way to keep a to-do list for my various alts. I don't however use any other feature of this addon, specifically the feature the addon is named for. Considering the two feature sets are only loosely connected, might I suggest splitting the addon into two? Or if someone else can suggest an equivalent addon/weak aura that replicates the experience of the tracking bar.

**Comment by Sluimerstand** [comment]
This is not something I am interested in doing.
