### ISSUE TITLE
Tooltip giving LUA Error

### ISSUE THREAD

**Issue by Neovik78** [Sluimerstand/ProfessionShoppingList#51]
since the last 2 updates when i mouse over items i always get an lua error(either with ArkInventory or TSM also in the LUA Error):

`
Message: ...ns/ProfessionShoppingList/ProfessionShoppingList.lua:613: attempt to index field '?' (a number value)
Time: Fri Jan 13 06:09:28 2023
Count: 6
Stack: ...ns/ProfessionShoppingList/ProfessionShoppingList.lua:613: attempt to index field '?' (a number value)
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/ProfessionShoppingList/ProfessionShoppingList.lua"]:613: in function <...ns/ProfessionShoppingList/ProfessionShoppingList.lua:592>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:282: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:240>
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:237: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/ArkInventory/Core/ArkInventoryTooltip.lua"]:308: in function <...ace/AddOns/ArkInventory/Core/ArkInventoryTooltip.lua:300>
[string "@Interface/AddOns/ArkInventory/Core/ArkInventoryTooltip.lua"]:457: in function `TooltipSet'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventory.lua"]:8857: in function `Frame_Item_OnEnter'
[string "*ArkInventory.xml:353_OnEnter"]:1: in function <[string "*ArkInventory.xml:353_OnEnter"]:1>

Locals: (*temporary) = true
(*temporary) = <function> defined =[C]:-1
`

**Comment by Sluimerstand** [comment]
@Neovik78 Are you on the latest version (019)? If yes, can you confirm if the error also occurs when PSL is the only addon loaded?

**Comment by Sluimerstand** [comment]
I found the issue. I'll put out a fix, in the meantime you can resolve it through running `/psl clear`.

**Comment by Neovik78** [comment]
thanks very much it`s working now with new version

**Comment by Neovik78** [comment]
ok only for some time then the error comes again :(

**Comment by Sluimerstand** [comment]
Does the error keep occurring after using `/psl clear`?

**Comment by Neovik78** [comment]
didn`t occured anymore i think i wasn`t on the latest version 
sorry thaught curse already updated it

**Comment by Sluimerstand** [comment]
Glad to hear it's solved now! :)
