### ISSUE TITLE
Lua Error with latest update

### ISSUE THREAD

**Issue by Gogadon** [Sluimerstand/ProfessionShoppingList#52]
Message: ...ns/ProfessionShoppingList/ProfessionShoppingList.lua:629: attempt to index field '?' (a number value)
Time: Fri Jan 13 19:15:44 2023
Count: 2
Stack: ...ns/ProfessionShoppingList/ProfessionShoppingList.lua:629: attempt to index field '?' (a number value)
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/ProfessionShoppingList/ProfessionShoppingList.lua"]:629: in function <...ns/ProfessionShoppingList/ProfessionShoppingList.lua:606>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:282: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:240>
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:237: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventoryTooltip.lua"]:308: in function <...ace/AddOns/ArkInventory/Core/ArkInventoryTooltip.lua:300>
[string "@Interface/AddOns/ArkInventory/Core/ArkInventoryTooltip.lua"]:457: in function `TooltipSet'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventory.lua"]:8857: in function `Frame_Item_OnEnter'
[string "*ArkInventory.xml:353_OnEnter"]:1: in function <[string "*ArkInventory.xml:353_OnEnter"]:1>

Locals: (*temporary) = true
(*temporary) = <function> defined =[C]:-1

**Comment by Sluimerstand** [comment]
Does the error keep occurring after using `/psl clear`?

**Comment by Gogadon** [comment]
After that he is gone! But this is not the solution to always enter /psl clear

**Comment by Sluimerstand** [comment]
It's because of some leftover stuff from previous versions, doing `/psl clear` once fixes it permanently. :)
