### ISSUE TITLE
Reagent Quality

### ISSUE THREAD

**Issue by DrD0cs** [Sluimerstand/ProfessionShoppingList#53]
hi,
thx 4 the update!
When i want to track a recipe, it show me just the reagent from the options. 
e.g. If i have one golden Item in my bag and i configure in the options silver, it kust show me in the reagent list 0/X items.
But i thought it is the minium quality ;) So it have to show 1/X or not?
Can you fix it?

Thanks!

**Comment by Sluimerstand** [comment]
You're right, that is not showing properly in the list! It should show properly in the item tooltips though, I'll fix this with the next release. :)

**Comment by DrD0cs** [comment]
Big Thx!
