### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by nilskus** [Sluimerstand/ProfessionShoppingList#60]
Upon loading, PSL throws up this error: https://pastebin.com/2mWpwmyC

Also, whenever I have a recipe tracked and I collect other items/resources from my mail, PSL randomly adds quantities to the tracked recipes but I can't seem to get an error code for that

**Comment by nilskus** [comment]
edit: https://pastebin.com/PPtG5ejq here's another one

and yes, I only have PSL loaded

**Comment by nilskus** [comment]
yes i eventually have to do that command so it stops throwing out errors. and the recipes do not matter, it happens with every single one sadly

**Comment by Sluimerstand** [comment]
Alright, then you are indeed on the latest version and have done the internal cleanup that is sometimes required when coming from older versions. It's strange it happens for every recipe you attempt to track though, as I cannot recreate that issue only running PSL.

Can you send me a copy of your `World of Warcraft\_retail_\WTF\Account\(YourAccount)\SavedVariables\ProfessionShoppingList.lua` file? That contains all the info PSL saves and should hopefully be able to show me what is causing the error for you.

**Comment by nilskus** [comment]
https://pastebin.com/HK9Y83w0

hope that helps!
thanks in advance for your effort and quick replies, PSL is truly one of my favorite addons and even if the "fatality" errors are killing me, I still can't get around it haha.

**Comment by Sluimerstand** [comment]
Mm, I cannot seem to recreate any of the issues you are describing even with your local settings, or find anything wrong with it.
Could you try deleting PSL and re-installing the addon? Maybe something went wrong with one of the previous installs that is causing these issues.

**Comment by nilskus** [comment]
The issue was "kind of" fixed after the hotfix before the last one from 4h ago. It did have some hiccups as you said, which were related to the vanilla tracking overlapping basically. 

I just reinstalled with the latest hotfix and so far everything seems to be working perfectly fine, and i hope it stays that way.

Thank you for your work, truly one of the nicest and most dedicated devs :)

**Comment by Sluimerstand** [comment]
10.0.5 changed something about how to (un)track recipes through the vanilla tracking, so that bit broke and was indeed causing some unexpected behaviours. Glad to hear a reinstall also resolved the other issues, I'm hoping it all stays working as well! :)
