### ISSUE TITLE
Feature Request: Globally Saved Position

### ISSUE THREAD

**Issue by nancikennedy** [Sluimerstand/ProfessionShoppingList#62]
Being able to set the position, have it remember that across alts and if you have to disable/re-enable the addon would be a very useful feature.

**Comment by Sluimerstand** [comment]
I'll have to see if I'm able to implement this, by default the window positions are saved in `WTF/Account/(Account)/(Server)/(Character)/layout-local.txt` so I'll need to look into how I can make that global. Should be possible!

**Comment by nancikennedy** [comment]
Awesome. I really wish Blizz would change how layout-local.txt works, so that it doesn't completely overwrite the file with only the loaded addons info.

**Comment by Sluimerstand** [comment]
Ah, I guess that explains why the window positions sometimes reset for me. I guess even for people who wouldn't use the option to have the positions be global this enhancement would be beneficial.

**Comment by Sluimerstand** [comment]
This will be included in the next version.
