### ISSUE TITLE
Quick order button remaining greyed out

### ISSUE THREAD

**Issue by SoulCookie** [Sluimerstand/ProfessionShoppingList#64]
Hi. I've been able to use the Quick Order button a handful of times, but lately it has remained greyed out even after opening alts' crafting windows.

Is there some hidden prerequisite that's changed which I'm missing?

PSL version is v10.0.5-005

**Comment by Sluimerstand** [comment]
It should just be the recipe cached and having a valid character name entered in the textbox. Can you send me copy of your `World of Warcraft\_retail_\WTF\Account\(Account Name)\SavedVariables\ProfessionShoppingList.lua` file? Maybe I messed something up in the code where it thinks one of these conditions is not met, when it actually is.

Also, is this the case for some recipes, or all recipes?

**Comment by SoulCookie** [comment]
Well, further research suggests that this may be purely a [PEBKAC](https://en.wikipedia.org/wiki/User_error#PEBKAC/PEBCAK/PICNIC) issue. 

It looks like I was misinterpreting the greyed-out Quick Order button **_with no valid crafter's name entered_** as meaning there were no valid recipient-crafters. When I entered a name, _hey! look at that!_, the button lights up.

So this issue _might_ be a tangentially related UI issue (and I'll leave that to you to consider), but the problem as I described it **does not exist**.

**This ticket can be closed.** Sorry for wasting your time. 😅

**Comment by Sluimerstand** [comment]
Haha, no worries, I can see about clarifying that a character name has to be entered in the text box to function as the recipient for the crafting order. That can definitely be considered a lacking or unclear feature of the UI.
