### ISSUE TITLE
Feature request: Option to use local reagents when submitting Quick Order to alt

### ISSUE THREAD

**Issue by SoulCookie** [Sluimerstand/ProfessionShoppingList#65]
As I said in my other ticket (#64), I _have_ been able to use the Quick Order a few times, but not recently.

One enhancement which I'd really love to see with Quick Orders is the option to use my current character's mats when submitting a Quick Order.

My use case came about after discovering I'd accidentally drained an overlarge amount of my scribe's Artisan's Mettle after ordering Draconic skill Treatises from them. Having the ability to say, "No, use my mats if I have them," like the default ordering method would be good.

Bonus points if you're somehow able to use the check/not-checked status of the on-screen reagents from the default ordering method UI.

PSL version is v10.0.5-005

**Comment by Sluimerstand** [comment]
This is something I want for myself as well, but I haven't figured out yet how to do this. :(
PSL basically uses this command, which Shoogen (the main dev for DataForAzeroth) figured out: `/run C_CraftingOrders.PlaceNewOrder({ skillLineAbilityID=47951, orderType=2, orderDuration=0, tipAmount=100, customerNotes="", orderTarget="NAME", reagentItems={}, craftingReagentItems={} })`

I _might_ be able to see how the info gets sent to the API, or maybe get the info from the recipe somehow. I'll look into it!

**Comment by Sluimerstand** [comment]
Will be included in the next version.
