### ISSUE TITLE
Feature Request: Add per character saved lists

### ISSUE THREAD

**Issue by LuckyBlob** [Sluimerstand/ProfessionShoppingList#66]
Hello,

It would be nice to have "per character" lists.

Also, it would be nice to have a "saved list" that is immutable of the actual working list. It could also be updated (once set as the working list) with what is in your bags.

**Comment by LuckyBlob** [comment]
I have taken the liberty to modify the code to make this work. It's wrapped with 
-- Update nlawson
-- end nlawson

I also took the liberty to add toggleable debug to have a semi callstack.

[ProfessionShoppingList.lua_lua.txt](https://github.com/Sluimerstand/ProfessionShoppingList/files/10864267/ProfessionShoppingList.lua_lua.txt)
[ProfessionShoppingList.lua_toc.txt](https://github.com/Sluimerstand/ProfessionShoppingList/files/10864268/ProfessionShoppingList.lua_toc.txt)

**Comment by Sluimerstand** [comment]
Oh, wonderful! I'd taken a look at it before, but I really need to set aside some time to go through it properly because I didn't understand some bits and I need to test with it so I can understand how it works exactly. Hopefully I can do this soon. Thanks again for the effort! <3

**Comment by LuckyBlob** [comment]
Yeah, I kind of "did it for me", but I tried to be vocal with my variables. Don't hesitate to ask me questions, I can answer exhaustively if you need.

**Comment by Sluimerstand** [comment]
Alright, I found a way, way simpler solution to this problem. Feature will be added with the next release. :)
