### ISSUE TITLE
Missing weekly profession knowledge

### ISSUE THREAD

**Issue by edemen** [Sluimerstand/ProfessionShoppingList#70]
Awesome addon!

Would be awesome if you could add more weekly knowledge drops:

Mining:
[Impenetrable Elemental Core](https://www.wowhead.com/item=204233/impenetrable-elemental-core)
[Heated Ore Sample](https://www.wowhead.com/item=194039/heated-ore-sample)
[Elementally-Charged Stone](https://www.wowhead.com/item=202011/elementally-charged-stone)
[Unyielding Stone Chunk](https://www.wowhead.com/item=194062/unyielding-stone-chunk)

Engineering
[Everflowing Antifreeze](https://www.wowhead.com/item=204227/everflowing-antifreeze)

Blacksmithing
[Dense Seaforged Javelin](https://www.wowhead.com/item=204230/dense-seaforged-javelin)

Also probably worth including knowledge drops from other professions from summoned rares in Forbidden Reach

Cheers

**Comment by Sluimerstand** [comment]
We were actually just talking about the profession rares the other day on the ATT Discord. We're going to check out this weekend whether or not the hidden tracking quests for those actually trigger on kill, loot, or use of the item, since we're not entirely sure yet whether or not they are actually weekly limited.

In a somewhat same vein (see this is funny because mining), I thought those Mining items were part of the ones that could drop rarely, but without any cooldown. I'll have to double-check how we ended up categorising them in ATT to see if they actually are weekly or not.

Because baseline, anything that is not weekly I can't track in the addon, not in a useful manner anyway. I'll look into it!

**Comment by edemen** [comment]
Makes sense. I forgot they didn't properly implement the weekly tracking stuff (e.g. you can track weekly rep turn in for fish but not for fishing tuskarr crafting materials).

But in the case we can't track these additional weekly knowledge drops, could we keep track of them in the local addon database? I imagine you could, provided that the user keeps the addon enabled. Would that be a viable alternative?

**Comment by Sluimerstand** [comment]
Alright, seems like I cannot track these items the normal way, and adding support to do so through the addon itself would be messy and unreliable. As for the old mentioned items, we've so far verified those are not weekly, but rare drops without a cooldown. If we do discover weekly tracking quests for them, I'll add them then. :)

**Comment by reddraggone9** [comment]
I've been use a Weak Aura for a while on several characters to track the weekly drops from the summoned rares in the Forbidden Reach. Maybe there's something I'm missing, but just in case this is useful.

| Quest ID | Item                        | Profession     | Rare              |
| -------- | --------------------------- | -------------- | ----------------- |
| 74935    | Draconic Suppression Powder | Alchemy        | Agni Blazehoof    |
| 74931    | Ancient Ceremonial Trident  | Blacksmithing  | Tidesmith Zarviss |
| 74927    | Glowing Crystal Bookmark    | Enchanting     | Manathema         |
| 74934    | Gnomish Voicebox            | Engineering    | Fimbol            |
| 74933    | Dormant Lifebloom Seeds     | Herbalism      | Kangalo           |
| 74932    | Arcane Dispelling Rune      | Inscription    | Arcantrix         |
| 74936    | Cyrstal Tuning Fork         | Jewelcrafting  | Amephyst          |
| 74928    | Reinforced Pristine Leather | Leatherworking | Snarfang          |
| 74926    | Amplified quaking Stone     | Mining         | Tectonus          |
| 74930    | Razor-Sharp Animal Bone     | Skinning       | Faunos            |
| 74929    | Traditional Morqut Kite     | Tailoring      | Gareed            |
