### ISSUE TITLE
Enhancement: Add button to add reagents to Auctionator shopping list window

### ISSUE THREAD

**Issue by Rezy942** [Sluimerstand/ProfessionShoppingList#74]
Hello,

As title suggests - would be great to replicate the current Auctionator feature to add tracked recipes to a shopping list.
This would be a massive improvement for the many Auctionator users :)
Also, a huge problem in my opinion - this addon completely hides default recipe tracking check mark.
This is an issue for all Auctionator users that rely on this feature, as they can no longer use it...

Please look into this :)

Thanks

Auctionator example:
![image](https://user-images.githubusercontent.com/122007087/233227267-b63ff1d2-21ed-4cac-8235-02d8eda3e6a2.png)

**Comment by Sluimerstand** [comment]
This is included in the next release, in the form of a list import function for Auctionator. With this, the fact that PSL overrides Blizzard's own tracking should also no longer be an issue, although it's a little more roundabout.

Blizzard's tracking is a little inconsistent especially with ranked recipes, so for PSL it is (I'm afraid) important to keep overriding that particular bit.
