### ISSUE TITLE
Mouseover with shortcuts in list window

### ISSUE THREAD

**Issue by Dreadful-Sanity** [Sluimerstand/ProfessionShoppingList#79]
I'm having a hard time remembering stuff. I would love a way to display the shortcuts from the actual list window instead of opening the settings every time. Maybe a little tooltip when hovering over the list title?

**Comment by Sluimerstand** [comment]
I think this should be possible and I like this idea a lot. I'll see if I can make this work for the next release!

**Comment by Sluimerstand** [comment]
This is included in the next release. :)
