### ISSUE TITLE
Add materials cost sum

### ISSUE THREAD

**Issue by Narthe** [Sluimerstand/ProfessionShoppingList#80]
Would be cool to have the gold sum of all the reagents at the bottom of your reagents list. Since you already have the AH price for each reagent, it would be a simple and very useful addition. My ideal use case would be to leave a recipe in my shopping list, just do an auctionator scan and have the gold total updated so I could compare the price change for a recipe.

**Comment by Sluimerstand** [comment]
Hi Narthe,
PSL actually does not have the AH prices of items. Likely it's Auctionator that adds that info to both the item tooltips and below the recipe information in your tradeskill windows, or possibly another addon. While I may at some point in the far future include pricing for the tracked reagents, this is not planned for now.
