### ISSUE TITLE
Unable to track mats for ReCraft

### ISSUE THREAD

**Issue by NewVenari** [Sluimerstand/ProfessionShoppingList#85]
I notice that when I try to Track mats required for a Recraft, I think I'm getting the mats shopping list for the original crafting of the item, instead of the mats needed to recraft the item. 
![PSL Recraft](https://github.com/Sluimerstand/ProfessionShoppingList/assets/61172315/a40282ac-4539-44d2-9cc4-fd4395bb5521)

**Comment by Sluimerstand** [comment]
I'll have another look at this, last time I did I could not figure out a way to make this work.
In a nutshell, PSL gets the info for the selected recipe and shows the reagents for that, whereas for recrafts this works very differently. Hopefully I can find some more concrete info about the recrafting order's reagents!

**Comment by Sluimerstand** [comment]
Okay this took a WHILE, but I've managed to fix it. I'll be testing it for a while longer to make sure before I release it, though. :)
