### ISSUE TITLE
Error when trying to Track with Tailoring

### ISSUE THREAD

**Issue by JoshuaAndrewN** [Sluimerstand/ProfessionShoppingList#87]
11x ...ns/ProfessionShoppingList/ProfessionShoppingList.lua:512: bad argument #1 to 'gsub' (string expected, got nil)
[string "=[C]"]: in function `gsub'
[string "@ProfessionShoppingList/ProfessionShoppingList.lua"]:512: in function `pslTrackRecipe'
[string "@ProfessionShoppingList/ProfessionShoppingList.lua"]:584: in function <...ns/ProfessionShoppingList/ProfessionShoppingList.lua:583>

Locals:
(*temporary) = nil
(*temporary) = " |A:Professions%-ChatIcon%-Quality%-Tier1:17:15::1|a"
(*temporary) = ""
(*temporary) = "string expected, got nil"

**Comment by Sluimerstand** [comment]
Have you tried using `/psl clear` yet?
Are you using the latest public release, or the latest Github version?
And what were you trying to track exactly (which Tailoring recipe(s)) and how (the crafting window button, slash command, shift+clicking)?

**Comment by Sluimerstand** [comment]
I surmised from my own changes that you were on the Git version and I also realised the issue. I just forgot how to write code and tried to refer to a local variable outside of its environment. It's fixed now! :)

**Comment by JoshuaAndrewN** [comment]
I apologize I completely forgot about opening this issue.  But thank you!!!!
