### ISSUE TITLE
NO bartered Journal

### ISSUE THREAD

**Issue by Barmiton** [Sluimerstand/ProfessionShoppingList#91]
there is no bartered journal for jewelcrafting , leatherworking , tailoring  and mining . Need to remove

**Comment by Sluimerstand** [comment]
Hi Barminton,
The bartered journals are bugged. Some can be seen by some, but not by others. Sometimes before the change to boulders, sometimes after. That does not mean they don't exist. For some folks they do.

I advise you to send in a bug report to Blizzard.
