### ISSUE TITLE
LUA Error: ProfessionShoppingList.lua 

### ISSUE THREAD

**Issue by fubaWoW** [Sluimerstand/ProfessionShoppingList#94]
hi there,

seems you got a typo at line ``1295`` in ``ProfessionShoppingList.lua``!

```
local settings = CreateFrame("Frame")			ft-
```
should just be
```
local settings = CreateFrame("Frame")
```

greetings

**Comment by Sluimerstand** [comment]
Hey @fubaWoW, I noticed that a few minutes after sending out the updated version. I somehow managed to fat-finger that into my code after testing and before saving, so that was fun. It's resolved by now, thank you for the heads-up anyway! :D
